language: cpp
sudo: false
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
            - libegl1-mesa-dev
            - libsdl2-dev
            - libglew-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libc++-dev
            - clang-5.0
            - libegl1-mesa-dev
            - libsdl2-dev
            - libglew-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build && cd build && cmake ..
  - make
